#!/bin/bash

# Path to sys.json file
sys_file_path="$HOME/ptfs/sys/sys.json"

# Check if sys.json file exists
if [ ! -e "$sys_file_path" ]; then
    echo "Error: sys.json file not found."
    exit 1
fi
# Read the status from sys.json
status=$(jq -r '.status' "$sys_file_path")

# Check if the status is off
if [ "$status" == "off" ]; then
    echo "System is off."
    exit 1
fi

# Vérifier le nombre d'arguments
if [ "$#" -ne 1 ]; then
    echo "Error: Incorrect number of arguments. Usage: $0 <file_name>"
    exit 1
fi

# Verifying if the file or the directory exists
if [[ $(realpath "$1") != ~/ptfs* || ! -e "$1" ]]; then

    echo " Error: Invalid file or directory."
    exit 1
fi

# Vérifier le type de fichier
if [ -d "$1" ]; then
    echo "$(realpath --relative-to="$HOME" "$1") is a directory"
elif [ -x "$1" ]; then
    echo "$(realpath --relative-to="$HOME" "$1") is an executable file."
else
    echo "$(realpath --relative-to="$HOME" "$1") is a non-executable file."
fi

